apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: camion-app
type: Opaque
data:
  jwt.secret: "c2VjcmV0LWtleS1mb3Itand0LXNpZ25pbmc=" # base64 encoded
  db.password: "bW9uZ28xMjM=" # base64 encoded
  api.key: "YXBpLXNlY3JldC1rZXk=" # base64 encoded